### ISSUE TITLE
Resize mode crashes on img2img

### ISSUE THREAD

**Issue by daanbouwman19** [sd-webui/stable-diffusion#147]
I get this error if I change resize mode to "crop and resize" or "resize and fill" on img2img.

`!!Runtime error (img2img)!!
 Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 4, 512, 512] to have 3 channels, but got 4 channels instead
exiting...calling os._exit(0)`

**Comment by hlky** [comment]
Notes: `RGBA` vs `RGB`?

**Comment by yourjelly** [comment]
For the record these modes were not causing this error previously.

**Comment by vdruts** [comment]
RuntimeError: The size of tensor a (135) must match the size of tensor b (64) at non-singleton dimension 3

**Comment by vinyvince** [comment]
Hola :)

I updated 2 days ago, with the new interface, i have so many issue with img to work...
I don't know, very capricious, most of the time with non mask option, it will just not work, complaining the following

 File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\components.py", line 1548, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\processing_utils.py", line 28, in decode_base64_to_image
    content = encoding.split(";")[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers

**Comment by busyfree** [comment]
same error too, default parameters with img2img，but when after do mask drawing then img2img can worked.
